name: Daily Update

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '45 21 * * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install FFMPEG Dependencies 🧑‍🏭
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install requests
          pip install -r requirements.txt
          pip list

      - name: Run Python script
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update live files" && git push)

    env:
      TZ: Asia/Shanghai